name: KiBot Export

on:
  push:
    paths:
      - 'pcb/*.kicad_sch'
      - 'pcb/*.kicad_pcb'
      - 'pcb/*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - 'pcb/**.kicad_sch'
      - 'pcb/**.kicad_pcb'
      - 'pcb/**.kibot.yaml'
      - '.github/workflows/kibot.yml'

jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:dev
    steps:
    - uses: actions/checkout@v3
    - name: Cache 3D Models
      id: models-cache
      uses: set-soft/cache@main
      with:
        path: ~/cache_3d
        key: cache_3d
    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: pcb/config.kibot.yaml
        schema: 'pcb/ultramote.kicad_sch'
        board: 'pcb/ultramote.kicad_pcb'
        dir: kibot_generated
        cache3D: YES
        targets: ibom.html bom.csv board.pdf schematic.pdf model.step top_render bottom_render
    - name: Install rsync
      run: |
        apt-get update && apt-get install -y rsync
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: kibot_generated
        target-folder: kibot_generated
